jwt_priv: |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyUIAO/1m47w6n
  VDcIJpTfqlDooU7yHVirDCoKSQ9TwU1zARMdObb6zH4RjoIWdjFK2WLARO2+q+Lq
  mVTzD/2sr+cPG4UOErB0a/YEdjsprfgUcxKbtgt0DpSXdCMMRo/D1/pEskpLK8+p
  L2J0A0X6V0+PdAElRan/B9Mun2knrWXWzHuJ9SAK6bydkf/r2cWv51ZBGTUycIMP
  DImH26Sc+XqK4FVaofP+3aQfhMYTElReptpLpQ/fidptCPFE6OEhlbmMaatTID2E
  feKYQpgjj2489WKQGNj9YzYNWnNjC6aPw50RFZ9ca5R2i5MhMUhi934kAIapClSV
  BP1os5cTAgMBAAECggEAdjNcoBRusmNtcEgn7rQ8jYNF/N8pCN+hLkly+Lxzd460
  u15kAESI4fl6PEMeQqt4g2hUyKUof/NLCT45DKJ2Aunbna0dZzXGWHZUb6K8FyXm
  RA//rs5fC0C7CSaIMRP5KtZZZP5WtzvEfR8XAVZGJeuIpsw8Eiv6wz65o7cyKoTv
  OEK4whPWGPBDdsiB/ERED/8OCFYwgjIVzwZVjgC9DAO0AAIrJW7Uox3XWRXP0RVi
  YKyF6fH2eod5WtlbKFTmE1Se4TjMViQhJGQIkLAqUZ/L6RmrSznH4Ndfr+FhJl/M
  DYHJlMA6r5S4NKApoXOrAnBefzKfnsQ7RCg1Zz8D4QKBgQDsmZ843HL3sxII/zNq
  NUdZMPpvTST6u9yYFYt7HNOG9AAuWvY4OVB7UlOhc2cB4zLXLMLXHb0/MQ1zgr8R
  +7Eb6SNIAst8RBDhPIhcEdj4Ye1+w2p105j9GpU8+LRliwvIdSTvtNVfN0lQ1nLE
  yIbmdLEJNwF2lLamkvSVG2ShUQKBgQDA722FZyOl7m4wZeAlEvObB4+B4LBwUigs
  nRe8tnUhyVUhbkzkvpc8TwST12RTutXYglDfRZhgxNfq5NPhjPkCiJQvL5D8keIC
  CrnnEW5Ee/81h1uaeUezO+DbMORw1QSe3GMbR/UV6aHPCOLSHrhYgG58nM0BNanH
  Z1Wn8/65IwKBgBmER+O+ArgsG9nUjBr8PAGmgpvWWhKgiB3u1OgmJ7n6PrrBHKTb
  qY5jRpm29HkDo8wJC8pfbrWN+MFobGroFiXIcwGlK4TvYlKoUJx9YEUJaq+tK6Ih
  e/JwF4BH4kzBPjgUSjN/8TMfp0yMlDwc1E+ubhlsUUAUsc4tMyuRlLzBAoGAX7Zn
  nsaL6MVf5KKlj77XGxGlH8lXvmEDjR5hqDzb3ucCVJNjkhb67/BDVRSFsQP/EmmT
  tS/RaDA+7UiX1E0bOyaGXOI8CxBUDq9Dil4bVd4tvWBpETkZWNFbu2GF8nO61xR+
  Fgqci0JcA1llLNgQm9ca+LbQ/MiicUnSNH/W3gECgYEA3nsIQwzkmcbVuYVq/Hch
  q31Qp/7Htt9Kix3adNNbi5Jnt5ABP3Dpyk79pVUxOi9pQ8HahTgwZgMTY4B7IAo3
  w+LHs++/2dr3bhIq6FZjC5s8ZDwvZi12+/N2cHWLFL9zyyBn7I/kiOxrEuOU2LMW
  leQVLUzYPvuR9Opbfe97Vq4=
  -----END PRIVATE KEY-----
jwt_pub: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAslCADv9ZuO8Op1Q3CCaU
  36pQ6KFO8h1YqwwqCkkPU8FNcwETHTm2+sx+EY6CFnYxStliwETtvqvi6plU8w/9
  rK/nDxuFDhKwdGv2BHY7Ka34FHMSm7YLdA6Ul3QjDEaPw9f6RLJKSyvPqS9idANF
  +ldPj3QBJUWp/wfTLp9pJ61l1sx7ifUgCum8nZH/69nFr+dWQRk1MnCDDwyJh9uk
  nPl6iuBVWqHz/t2kH4TGExJUXqbaS6UP34nabQjxROjhIZW5jGmrUyA9hH3imEKY
  I49uPPVikBjY/WM2DVpzYwumj8OdERWfXGuUdouTITFIYvd+JACGqQpUlQT9aLOX
  EwIDAQAB
  -----END PUBLIC KEY-----
